### ISSUE TITLE
Thanks for gdbForPackages

### ISSUE THREAD

**Issue by pjones** [timor/timor-overlay#3]
I just want to thank you for your `gdbForPackages` function.

The only thing that would make it better is if it were in its own repo to make it easier for me to use.  For now I've just copied the code into my personal nixpkgs repo.

Thanks!!

**Comment by timor** [comment]
For starters, I put it into its own file in 14ac212fe19969a7b1855831b4e48fa6fca88153.

Does that help in any way?

**Comment by pjones** [comment]
Yes.  Thank makes it easier to reuse.  Thanks!
